[project]
name = "hexo"
version = "0.2.1"
description = "A fast, reusable Python engine for Hexo on an infinite hex grid."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Pierre LAPOLLA"}
]
keywords = [
    "hexo",
    "board-game",
    "game-engine",
    "hex-grid",
    "connect-six",
    "ai",
]
requires-python = ">=3.10"
dependencies = [
    "pedros>=0.12.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=3.7.1",
    "pytest-benchmark>=5.1.0",
    "pytest>=8.3.5",
    "pytest-cov>=7.0.1",
    "rich>=14.3.3",
    "ruff>=0.15.8",
]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q --cov=. --cov-report=html"
testpaths = ["tests"]
pythonpath = ["src"]
